name: Tests
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master
    paths-ignore:
      - ".github/**"
      - "!.github/workflows/main.yml"
      - "docs/**"
      - "*.md"
      - ".git*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install test dependencies
        run: |
          python -m pip install -U pip
          python -m pip install -e .[dev]
      - name: Run pytest
        run: |
          pytest
